### ISSUE TITLE
WEBSITE: broken layout

### ISSUE THREAD

**Issue by Lol1chw** [feature-sliced/documentation#604] opened 2023-07-14 12:05 UTC
![image](https://github.com/feature-sliced/documentation/assets/94941930/0c725bcc-3d6e-4c72-aa92-86aa8bf86652)
![image](https://github.com/feature-sliced/documentation/assets/94941930/fdab74e3-43e3-4247-8bb0-ac23178ca761)
<br>
Unreadable text on a transparent background and broken layout.
Example page

**Comment by illright** [comment] 2023-09-02 20:18
Hey, sorry for the delay in response. I don't see these blurred out images myself. What browser are you using? Is it any browser extension that does that?

**Comment by Lol1chw** [comment] 2023-09-04 05:05
Hi,
I'm using Chrome browser, not using any media related extensions.
I think this behavior is due to the fact that I opened the https://feature-sliced.design/ru/examples tab and immediately minimized it before it fully loaded and came back to it after 10-15 minutes.

**Comment by illright** [comment] 2023-09-04 20:08
Hey, I tried your steps but still couldn't reproduce. Not with minimizing, not with throttling. How often does this happen for you? Would you say it's a critical issue or something that can easily be worked around?

**Comment by Lol1chw** [comment] 2023-09-07 11:53
I tried to reproduce this issue in a slightly different way. 
I tested it using the performance tab in devtools. I set the following parameters: Network: Slow 3G, CPU: 4x slowdown.
I came to the conclusion that this is how lazy loading of images works, but if the tab is minimized before the full load, then lazy loading does not work completely and images are not loaded afterwards.
However, there is a difference, if you reproduce the bug manually, there is an option to load these images manually by clicking on the images, but if the bug occurs accidentally, this option is absent and you have to reload the page. 
I think it's definitely not a critical issue, I opened the issue rather to find out why it happens.

**Comment by illright** [comment] 2023-09-14 16:53
I don't know why this could happen, but it probably has to do with docusaurus. Seeing as this is not a critical issue and we want to replace docusaurus at some point, I'll close this.

**Closed** 2023-09-14 16:53 UTC
